development:
  db:
    name: 'blog.db'
    adapter: 'sqlite'
    connection_line: 'sqlite://temp/blog.db'
test:
  db:
    name: 'blog.db'
    adapter: 'sqlite'
    connection_line: 'sqlite://temp/test_blog.db'
